trigger:
- master
name: $(Year:yy)$(DayOfYear)$(Rev:r)
variables:
  majorVer: '1.13.1'

stages:
  - stage: Unit_Test
    jobs:

    - job: 'Test_Linux'
      pool:
        vmImage: 'Ubuntu-16.04'
      strategy:
        matrix:
          Python36:
            python.version: '3.6'
          Python37:
            python.version: '3.7'
          Python38:
            python.version: '3.8'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install --pre pytest-azurepipelines==1.0.0rc1
          pip install flit mock codecov pydocstyle pytest-cov
          flit install
        displayName: 'Install dependencies'

      - script: |
          python -m pytest test/ --cov=wily/
          codecov
        displayName: 'pytest'
        env:
          CODECOV_TOKEN: '48f9ff3a-6358-4607-aa5d-9cb7cada539c'

      - script: pydocstyle --ignore=D301,D212,D203 wily
        displayName: 'pydocstyle'

    - job: 'Test_Windows'
      pool:
        vmImage: 'vs2017-win2016'
      strategy:
        matrix:
          Python36:
            python.version: '3.6'
          Python37:
            python.version: '3.7'
          Python38:
            python.version: '3.8'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip
          pip install flit mock codecov pytest pytest-cov
          flit install
        displayName: 'Install dependencies'

      - script: |
          pip install --pre pytest-azurepipelines==1.0.0rc1
          python -m pytest test --cov=wily
        displayName: 'pytest'

  - stage: Package_Test
    jobs:

    - job: 'Test_Linux_Packaging'
      pool:
        vmImage: 'Ubuntu-16.04'
      strategy:
        matrix:
          Python36:
            python.version: '3.6'
          Python37:
            python.version: '3.7'
          Python38:
            python.version: '3.8'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: python -m pip install --upgrade pip flit

      - script: "flit build"
        displayName: 'Build package and dependencies'
    - job: 'Test_Windows_Packaging'
      pool:
        vmImage: 'vs2017-win2016'
      strategy:
        matrix:
          Python36:
            python.version: '3.6'
          Python37:
            python.version: '3.7'
          Python38:
            python.version: '3.8'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: python -m pip install --upgrade pip flit

      - script: "flit build"
        displayName: 'Build package and dependencies'
